# Generated by Django 4.2.27 on 2025-12-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_borrower", models.CharField(max_length=100)),
                ("mail_borrower", models.EmailField(max_length=254)),
                ("number_of_card_librairies", models.CharField(max_length=50)),
                ("date_loan", models.DateTimeField(auto_now_add=True)),
                ("date_limit_return", models.DateTimeField(blank=True, null=True)),
                ("date_returned", models.DateTimeField(blank=True, null=True)),
                ("state_book_returned", models.CharField(blank=True, max_length=100)),
                ("comments", models.TextField(blank=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="books.book",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date_returned__isnull", True)),
                fields=("book",),
                name="unique_active_loan_per_book",
            ),
        ),
    ]
