# Generated by Django 4.2.27 on 2025-12-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="loan",
            name="unique_active_loan_per_book",
        ),
    ]
