# Generated by Django 4.2.27 on 2025-12-30 06:55

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                (
                    "published_date",
                    models.DateField(
                        validators=[books.models.validate_publication_year]
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "number_of_books_available",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            books.models.validate_number_of_books_available_less_than_possessed
                        ],
                    ),
                ),
                ("number_of_book_possessed", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("langage", models.CharField(blank=True, max_length=50)),
                ("number_of_pages", models.PositiveIntegerField(blank=True, null=True)),
                ("house_of_edition", models.CharField(blank=True, max_length=100)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="authors.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
