# Generated by Django 4.2.27 on 2025-12-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("birth_date", models.DateField()),
                ("nationality", models.CharField(max_length=100)),
                ("biography", models.TextField(blank=True)),
                ("date_dead", models.DateField(blank=True, null=True)),
                ("url_reference", models.URLField(blank=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name"), name="unique_author_fullname"
            ),
        ),
    ]
